# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-28 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ManyToManyField(to='app_permission.Role'),
        ),
    ]
