# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0002_auto_20180328_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='perm',
        ),
        migrations.RemoveField(
            model_name='role_perm',
            name='permission_id',
        ),
        migrations.RemoveField(
            model_name='role_perm',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='Role_Perm',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
