# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0004_auto_20180404_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url_name',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
