# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-09 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0009_auto_20180408_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='display_icon',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
