# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0013_auto_20180410_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmenuitem',
            old_name='root_item_order',
            new_name='display_order',
        ),
    ]
