# Generated by Django 2.1.1 on 2018-09-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountedCompany',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='客户号')),
                ('name', models.CharField(max_length=128, verbose_name='账户名称')),
                ('has_base_acc', models.BooleanField(default=False, verbose_name='是否基本户')),
                ('has_credit', models.BooleanField(default=False, verbose_name='是否有贷户')),
                ('sum_settle', models.IntegerField(default=0, verbose_name='累计结算量')),
                ('inter_settle', models.IntegerField(default=0, verbose_name='国际结算量')),
            ],
            options={
                'verbose_name_plural': '已开户对公客户',
            },
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '账户状态',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '客户类别',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='部门编号')),
                ('caption', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('display_order', models.SmallIntegerField(unique=True, verbose_name='排序先后')),
            ],
            options={
                'verbose_name_plural': '部门（综合）',
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '存款类型',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '区域',
            },
        ),
        migrations.CreateModel(
            name='DividedCompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, verbose_name='账号')),
                ('rate', models.FloatField(default=0, verbose_name='利率（%）')),
                ('transfer_price', models.FloatField(default=0, verbose_name='资金转移价（%）')),
                ('rate_spread', models.FloatField(default=0, verbose_name='利差（%）')),
                ('base_rate', models.FloatField(default=0, verbose_name='人行基准利率（%）')),
                ('floating_ratio', models.FloatField(default=0, verbose_name='人行基准上浮比例（%）')),
                ('acc_open_date', models.DateField(blank=True, null=True, verbose_name='开户日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='起始日期')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('data_date', models.DateField(verbose_name='数据日期')),
                ('divided_amount', models.IntegerField(default=0, verbose_name='分配余额（万元）')),
                ('divided_md_avg', models.IntegerField(default=0, verbose_name='本月分配日均（万元）')),
                ('divided_sd_avg', models.IntegerField(default=0, verbose_name='本季分配日均（万元）')),
                ('divided_yd_avg', models.IntegerField(default=0, verbose_name='本年分配日均（万元）')),
                ('acc_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.AccountStatus', verbose_name='账户状态')),
            ],
            options={
                'verbose_name_plural': '存款分配表',
            },
        ),
        migrations.CreateModel(
            name='GovernmentPlatformLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '平台级别',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='行业代码')),
                ('caption', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '行业门类',
            },
        ),
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '存款口径',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '企业规模',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='代号')),
                ('caption', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('gov_plat_lev', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.GovernmentPlatformLevel', verbose_name='平台级别')),
            ],
            options={
                'verbose_name_plural': '系列',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='姓名')),
                ('staff_level', models.SmallIntegerField(blank=True, null=True, verbose_name='行员等级')),
                ('phone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('cellphone_number', models.CharField(blank=True, max_length=16, null=True)),
                ('oa', models.CharField(blank=True, max_length=8, null=True)),
                ('yellow_red_card', models.IntegerField(default=0, verbose_name='授信到期黄红牌')),
                ('red_card_expire_date', models.DateField(blank=True, null=True, verbose_name='红牌到期日')),
            ],
            options={
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('sd_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='部门编号')),
                ('caption', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name_plural': '部门（细分）',
            },
        ),
        migrations.CreateModel(
            name='TypeOf3311',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('level', models.CharField(blank=True, max_length=16, null=True)),
                ('remark', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'verbose_name_plural': '3311类型',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.SubDepartment', verbose_name='部门（细分）'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Staff', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Department', verbose_name='部门（综合）'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='deposit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.DepositType', verbose_name='存款类型'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='rate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.RateType', verbose_name='存款口径'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.SubDepartment', verbose_name='部门（细分）'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='customer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.CustomerType', verbose_name='客户类别'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.District', verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Industry', verbose_name='行业门类'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Scale', verbose_name='规模'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Series', verbose_name='企业系列'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='type_of_3311',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.TypeOf3311', verbose_name='3311类型'),
        ),
    ]
