# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0003_auto_20180316_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='caption',
            field=models.CharField(max_length=16),
        ),
    ]
