# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0007_auto_20180323_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeof3311',
            name='level',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
