# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-13 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0009_auto_20180413_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='display_order',
            field=models.SmallIntegerField(unique=True, verbose_name='排序先后'),
        ),
    ]
