# Generated by Django 2.0.2 on 2018-05-07 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0011_auto_20180502_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountedPerson',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='客户号')),
                ('name', models.CharField(max_length=128, verbose_name='账户名称')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='派生自')),
            ],
        ),
        migrations.CreateModel(
            name='DividedPersonalAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divided_amount', models.IntegerField(default=0, verbose_name='分配余额（万元）')),
                ('divided_md_avg', models.IntegerField(default=0, verbose_name='本月分配日均（万元）')),
                ('divided_sd_avg', models.IntegerField(default=0, verbose_name='本季分配日均（万元）')),
                ('divided_yd_avg', models.IntegerField(default=0, verbose_name='本年分配日均（万元）')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='员工')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedPerson', verbose_name='客户')),
                ('rate_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.RateType', verbose_name='存款口径')),
            ],
        ),
    ]
