# Generated by Django 2.0.2 on 2018-05-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0012_accountedperson_dividedpersonalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountedperson',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='dividedpersonalaccount',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='dividedpersonalaccount',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='dividedpersonalaccount',
            name='rate_type',
        ),
        migrations.DeleteModel(
            name='AccountedPerson',
        ),
        migrations.DeleteModel(
            name='DividedPersonalAccount',
        ),
    ]
