# Generated by Django 2.0.2 on 2018-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0023_typeof3311_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='yellow_red_card',
            field=models.IntegerField(default=0, verbose_name='授信到期黄红牌'),
        ),
    ]
