# Generated by Django 2.0.4 on 2018-08-20 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0026_auto_20180725_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('display_order',), 'verbose_name_plural': '部门（综合）'},
        ),
    ]
