# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountedCompany',
            fields=[
                ('customer_id', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='客户号')),
                ('name', models.CharField(max_length=128, verbose_name='账户名称')),
                ('has_base_acc', models.BooleanField(default=False, verbose_name='是否基本户')),
                ('has_credit', models.BooleanField(default=False, verbose_name='是否有贷户')),
            ],
            options={
                'verbose_name_plural': '已开户对公客户',
            },
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '账户状态',
            },
        ),
        migrations.CreateModel(
            name='CreditLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_date', models.DateField(auto_now_add=True, verbose_name='数据日期')),
                ('credit_type', models.SmallIntegerField(choices=[(1, '组合额度'), (2, '专项额度')], default=1, verbose_name='授信种类')),
                ('apply_fanci', models.IntegerField(default=1, verbose_name='申报金额')),
                ('approved_by', models.SmallIntegerField(default=1, verbose_name='审批行处')),
                ('guar_type', models.CharField(max_length=32, verbose_name='担保方式')),
                ('approved_date', models.DateField(blank=True, null=True, verbose_name='审批日期')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='授信到期日')),
                ('specially_fanci', models.IntegerField(default=0, verbose_name='已批专项额度')),
                ('combine_fanci', models.IntegerField(default=0, verbose_name='已批组合额度')),
                ('combine_net_fanci', models.IntegerField(default=0, verbose_name='已批组合净额')),
                ('loan_fanci', models.IntegerField(default=0, verbose_name='已批贷款额度')),
                ('tangible_fanci_01', models.IntegerField(default=0, verbose_name='已批经营性物业抵押贷款')),
                ('tangible_fanci_02', models.IntegerField(default=0, verbose_name='已批城镇化建设贷款')),
                ('tangible_fanci_03', models.IntegerField(default=0, verbose_name='已批基本建设贷款')),
                ('tangible_fanci_04', models.IntegerField(default=0, verbose_name='已批外币流动资金贷款')),
                ('tangible_fanci_05', models.IntegerField(default=0, verbose_name='已批流动资金贷款')),
                ('tangible_fanci_06', models.IntegerField(default=0, verbose_name='已批房地产开发贷款')),
                ('tangible_fanci_07', models.IntegerField(default=0, verbose_name='已批银行承兑汇票')),
                ('tangible_fanci_08', models.IntegerField(default=0, verbose_name='已批贸易融资授信')),
                ('tangible_fanci_09', models.IntegerField(default=0, verbose_name='已批保函授信')),
                ('tangible_fanci_10', models.IntegerField(default=0, verbose_name='已批商票')),
                ('tangible_fanci_11', models.IntegerField(default=0, verbose_name='已批票贷通承诺')),
                ('tangible_fanci_12', models.IntegerField(default=0, verbose_name='已批票贷通贷款')),
                ('total_used', models.IntegerField(default=0, verbose_name='用信合计')),
                ('loan_used', models.IntegerField(default=0, verbose_name='贷款用信')),
                ('loan_avg', models.FloatField(default=0, verbose_name='贷款日均')),
                ('rate_avg', models.FloatField(default=0, verbose_name='加权利率')),
                ('used_tangible_fanci_01', models.IntegerField(default=0, verbose_name='已用经营性物业抵押贷款')),
                ('used_tangible_fanci_02', models.IntegerField(default=0, verbose_name='已用城镇化建设贷款')),
                ('used_tangible_fanci_03', models.IntegerField(default=0, verbose_name='已用基本建设贷款')),
                ('used_tangible_fanci_04', models.IntegerField(default=0, verbose_name='已用外币流动资金贷款')),
                ('used_tangible_fanci_05', models.IntegerField(default=0, verbose_name='已用流动资金贷款')),
                ('used_tangible_fanci_06', models.IntegerField(default=0, verbose_name='已用房地产开发贷款')),
                ('used_tangible_fanci_07', models.IntegerField(default=0, verbose_name='已用银行承兑汇票')),
                ('used_tangible_fanci_08', models.IntegerField(default=0, verbose_name='已用贸易融资授信')),
                ('used_tangible_fanci_09', models.IntegerField(default=0, verbose_name='已用保函授信')),
                ('used_tangible_fanci_10', models.IntegerField(default=0, verbose_name='已用商票')),
                ('used_tangible_fanci_11', models.IntegerField(default=0, verbose_name='已用票贷通承诺')),
                ('used_tangible_fanci_12', models.IntegerField(default=0, verbose_name='已用票贷通贷款')),
                ('approve_text', models.TextField(blank=True, null=True, verbose_name='批复内容')),
                ('is_green_finance', models.BooleanField(default=False, verbose_name='是否绿色金融')),
                ('credit_file', models.CharField(blank=True, max_length=16, null=True, verbose_name='信贷文件编号')),
                ('cp_consult_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='授信参考编号')),
            ],
            options={
                'verbose_name_plural': '授信审批台账',
            },
        ),
        migrations.CreateModel(
            name='CreditProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '授信性质',
            },
        ),
        migrations.CreateModel(
            name='CreditRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '信用评级',
            },
        ),
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': '客户类别',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='部门编号')),
                ('caption', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('address', models.CharField(blank=True, max_length=64, null=True, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '部门（综合）',
            },
        ),
        migrations.CreateModel(
            name='DepositType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '存款类型',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': '区域',
            },
        ),
        migrations.CreateModel(
            name='DividedCompanyAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=64, verbose_name='账号')),
                ('rate', models.FloatField(default=0, verbose_name='利率（%）')),
                ('transfer_price', models.FloatField(default=0, verbose_name='资金转移价（%）')),
                ('rate_spread', models.FloatField(default=0, verbose_name='利差（%）')),
                ('base_rate', models.FloatField(default=0, verbose_name='人行基准利率（%）')),
                ('floating_ratio', models.FloatField(default=0, verbose_name='人行基准上浮比例（%）')),
                ('acc_open_date', models.DateField(blank=True, null=True, verbose_name='开户日期')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='起始日期')),
                ('exp_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('data_date', models.DateField(verbose_name='数据日期')),
                ('divided_amount', models.IntegerField(default=0, verbose_name='分配余额（万元）')),
                ('divided_md_avg', models.IntegerField(default=0, verbose_name='本月分配日均（万元）')),
                ('divided_sd_avg', models.IntegerField(default=0, verbose_name='本季分配日均（万元）')),
                ('divided_yd_avg', models.IntegerField(default=0, verbose_name='本年分配日均（万元）')),
                ('acc_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.AccountStatus', verbose_name='账户状态')),
            ],
            options={
                'verbose_name_plural': '存款分配表',
            },
        ),
        migrations.CreateModel(
            name='EconomicProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '企业经济性质',
            },
        ),
        migrations.CreateModel(
            name='GovernmentPlatformLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '平台级别',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='行业代码')),
                ('caption', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '行业门类',
            },
        ),
        migrations.CreateModel(
            name='RateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': '存款口径',
            },
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': '企业规模',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='代号')),
                ('caption', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('gov_plat_lev', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.GovernmentPlatformLevel', verbose_name='平台级别')),
            ],
            options={
                'verbose_name_plural': '系列',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='工号')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='姓名')),
                ('staff_level', models.SmallIntegerField(blank=True, null=True, verbose_name='行员等级')),
                ('position', models.SmallIntegerField(choices=[(1, '支行员工'), (2, '支行负责人'), (3, '分行')], default=1, verbose_name='职务')),
                ('gender', models.SmallIntegerField(choices=[(1, '未填'), (2, '女'), (3, '男')], default=1, verbose_name='性别')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='出生年月')),
                ('political_status', models.SmallIntegerField(choices=[(1, '未填'), (2, '其他'), (3, '吃瓜群众'), (4, '少先队员'), (5, '共青团员'), (6, '入党积极分子'), (7, '预备党员'), (8, '党员'), (9, '资深党员')], default=1, verbose_name='政治面貌')),
                ('begin_work', models.DateField(blank=True, null=True, verbose_name='参加工作')),
                ('mail_address', models.CharField(blank=True, max_length=16, null=True, verbose_name='OA邮箱')),
                ('telephone', models.CharField(blank=True, max_length=16, null=True, verbose_name='固定电话')),
                ('cellphone', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='移动电话')),
            ],
            options={
                'verbose_name_plural': '员工信息',
            },
        ),
        migrations.CreateModel(
            name='SubDepartment',
            fields=[
                ('sd_code', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='部门编号')),
                ('caption', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name_plural': '部门（细分）',
            },
        ),
        migrations.CreateModel(
            name='TypeOf3311',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '3311类型',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.SubDepartment', verbose_name='部门（细分）'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Staff', verbose_name='员工'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Department', verbose_name='部门（综合）'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='deposit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.DepositType', verbose_name='存款类型'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='rate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.RateType', verbose_name='存款口径'),
        ),
        migrations.AddField(
            model_name='dividedcompanyaccount',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.SubDepartment', verbose_name='部门（细分）'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='credit_prop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.CreditProperty', verbose_name='授信性质'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='credit_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.CreditRate', verbose_name='信用评级'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.AccountedCompany', verbose_name='客户名称'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='department',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, to='root_db.Department', verbose_name='营销部门'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='economic_prop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.EconomicProperty', verbose_name='经济性质'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Staff', verbose_name='客户经理'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='customer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.CustomerType', verbose_name='客户类别'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.District', verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Industry', verbose_name='行业门类'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Scale', verbose_name='规模'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='series',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Series', to_field='code', verbose_name='企业系列'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='type_of_3311',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.TypeOf3311', verbose_name='3311类型'),
        ),
    ]
