# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0002_auto_20180316_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='id',
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='series',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.DO_NOTHING, to='root_db.Series', verbose_name='企业系列'),
        ),
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True, verbose_name='代号'),
        ),
    ]
