# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0004_auto_20180316_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountedcompany',
            name='inter_settle',
            field=models.IntegerField(default=0, verbose_name='国际结算量'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='sum_settle',
            field=models.IntegerField(default=0, verbose_name='累计结算量'),
        ),
    ]
