# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-16 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0005_auto_20180316_1628'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditledger',
            options={'verbose_name_plural': '授信台账'},
        ),
        migrations.AddField(
            model_name='creditledger',
            name='direct_financing',
            field=models.IntegerField(default=0, verbose_name='直接融资余额'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='direct_financing_remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='直接融资备注'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='escrow_amount',
            field=models.IntegerField(default=0, verbose_name='资金监管金额'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='escrow_remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='资金监管备注'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='invest_banking_amount',
            field=models.IntegerField(default=0, verbose_name='投行业务余额'),
        ),
        migrations.AddField(
            model_name='creditledger',
            name='invest_banking_remark',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='投行业务备注'),
        ),
    ]
