# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-23 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0006_auto_20180316_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='address',
        ),
        migrations.AddField(
            model_name='department',
            name='built_order',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='成立先后'),
        ),
    ]
