# Generated by Django 2.0.4 on 2018-05-02 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0010_auto_20180413_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditledger',
            name='department',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='营销部门'),
        ),
    ]
