# Generated by Django 2.0.2 on 2018-05-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0017_auto_20180507_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
    ]
