# Generated by Django 2.0.2 on 2018-05-09 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0020_auto_20180509_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='code',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='代号'),
        ),
    ]
