# Generated by Django 2.0.2 on 2018-06-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0021_auto_20180509_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='oa',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
