# Generated by Django 2.0.2 on 2018-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0022_auto_20180620_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeof3311',
            name='remark',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
