# Generated by Django 2.0.2 on 2018-07-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0025_staff_red_card_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='red_card_start_date',
        ),
        migrations.AddField(
            model_name='staff',
            name='red_card_expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='红牌到期日'),
        ),
    ]
