# Generated by Django 2.1.1 on 2018-09-26 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0027_auto_20180820_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': '员工', 'verbose_name_plural': '员工'},
        ),
    ]
