# Generated by Django 2.1.1 on 2018-09-28 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0028_auto_20180926_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountedperson',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='dividedpersonalaccount',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='dividedpersonalaccount',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='dividedpersonalaccount',
            name='rate_type',
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='customer_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.CustomerType', verbose_name='客户类别'),
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.District', verbose_name='区域'),
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='industry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.Industry', verbose_name='行业门类'),
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='scale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.Scale', verbose_name='规模'),
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='series',
            field=models.ForeignKey(blank=True, default='NONE', null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Series', verbose_name='企业系列'),
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='type_of_3311',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.TypeOf3311', verbose_name='3311类型'),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='credit_prop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.CreditProperty', verbose_name='授信性质'),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='credit_rate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.CreditRate', verbose_name='信用评级'),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.AccountedCompany', verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='department',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, to='root_db.Department', verbose_name='营销部门'),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='economic_prop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.EconomicProperty', verbose_name='经济性质'),
        ),
        migrations.AlterField(
            model_name='creditledger',
            name='staff',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff', verbose_name='客户经理'),
        ),
        migrations.AlterField(
            model_name='dividedcompanyaccount',
            name='acc_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.AccountStatus', verbose_name='账户状态'),
        ),
        migrations.AlterField(
            model_name='dividedcompanyaccount',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff', verbose_name='员工'),
        ),
        migrations.AlterField(
            model_name='dividedcompanyaccount',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='dividedcompanyaccount',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.Department', verbose_name='部门（综合）'),
        ),
        migrations.AlterField(
            model_name='dividedcompanyaccount',
            name='deposit_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.DepositType', verbose_name='存款类型'),
        ),
        migrations.AlterField(
            model_name='dividedcompanyaccount',
            name='rate_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.RateType', verbose_name='存款口径'),
        ),
        migrations.AlterField(
            model_name='dividedcompanyaccount',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.SubDepartment', verbose_name='部门（细分）'),
        ),
        migrations.AlterField(
            model_name='series',
            name='gov_plat_lev',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='root_db.GovernmentPlatformLevel', verbose_name='平台级别'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='sub_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.SubDepartment', verbose_name='部门（细分）'),
        ),
        migrations.AlterField(
            model_name='subdepartment',
            name='superior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.Department', verbose_name='所属部门'),
        ),
        migrations.DeleteModel(
            name='AccountedPerson',
        ),
        migrations.DeleteModel(
            name='DividedPersonalAccount',
        ),
    ]
