# Generated by Django 2.1.1 on 2019-01-09 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0029_auto_20180928_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('dcms_customer_num', models.CharField(blank=True, max_length=8, null=True, verbose_name='客户号')),
                ('cf_num', models.CharField(blank=True, max_length=16, null=True, verbose_name='信贷文件')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.District', verbose_name='区域')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Industry', verbose_name='行业')),
            ],
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='belong_to',
            field=models.IntegerField(choices=[(0, '员工'), (1, '部门')], default=0, verbose_name='归属'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff', verbose_name='管户人'),
        ),
        migrations.AddField(
            model_name='accountedcompany',
            name='sub_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.SubDepartment', verbose_name='经营部门'),
        ),
        migrations.AddField(
            model_name='customer',
            name='kernel_num',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.AccountedCompany', verbose_name='核心客户号'),
        ),
        migrations.AddField(
            model_name='customer',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff', verbose_name='管户人'),
        ),
    ]
