# Generated by Django 2.1.1 on 2019-01-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0030_auto_20190109_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountedcompany',
            name='belong_to',
            field=models.IntegerField(choices=[(0, '部门'), (1, '员工')], default=0, verbose_name='归属'),
        ),
    ]
