# Generated by Django 2.1.1 on 2019-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0031_auto_20190117_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountedcompany',
            name='dcms_customer_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='信贷系统客户编号'),
        ),
    ]
