# Generated by Django 2.1.1 on 2019-02-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20190214_1603'),
        ('root_db', '0033_auto_20190214_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='kernel_num',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
