# Generated by Django 2.1.1 on 2019-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0036_staff_dcms_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='dcms_name_gr',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='个人信贷系统用户名'),
        ),
        migrations.AddField(
            model_name='staff',
            name='dcms_name_sme',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='小微信贷系统用户名'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='dcms_name',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='地区信贷系统用户名'),
        ),
    ]
