# Generated by Django 2.1.1 on 2019-03-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0038_auto_20190306_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountedcompany',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
