# Generated by Django 2.1.1 on 2019-05-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0041_auto_20190326_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountedcompany',
            options={'verbose_name_plural': '已开户'},
        ),
        migrations.AlterField(
            model_name='accountedcompany',
            name='dcms_customer_code',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='信贷系统客户编号'),
        ),
    ]
