# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-11 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root_db', '0008_typeof3311_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='企业名称')),
                ('sub_industry', models.CharField(blank=True, max_length=64, null=True, verbose_name='细分行业')),
                ('taxes', models.PositiveIntegerField(verbose_name='纳税金额（万元）')),
                ('taxes_rank', models.PositiveSmallIntegerField(verbose_name='纳税排名')),
                ('inlet', models.PositiveIntegerField(verbose_name='进口额（万美元）')),
                ('export', models.PositiveIntegerField(verbose_name='出口额（万美元）')),
                ('in_port', models.PositiveIntegerField(verbose_name='进出口额（万美元）')),
                ('in_port_rank', models.PositiveSmallIntegerField(verbose_name='进出口排名')),
                ('claimer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='认领状态')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.District', verbose_name='区域')),
                ('industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Industry', verbose_name='行业')),
                ('type_of_3311', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.TypeOf3311', verbose_name='3311类型')),
            ],
            options={
                'verbose_name_plural': '客户库',
            },
        ),
    ]
