# Generated by Django 2.1.1 on 2018-09-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root_db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='企业名称')),
                ('simple_name', models.CharField(max_length=32, unique=True, verbose_name='企业简称')),
                ('credit_file', models.CharField(blank=True, max_length=16, null=True, verbose_name='信贷文件')),
                ('is_strategy', models.BooleanField(verbose_name='是否战略客户')),
                ('stockholder', models.IntegerField(choices=[(10, '国有'), (20, '民营'), (30, '外资')], verbose_name='控股方式')),
                ('tax_years', models.CharField(blank=True, max_length=64, null=True, verbose_name='纳税大户年份')),
                ('inter_clearing_years', models.CharField(blank=True, max_length=64, null=True, verbose_name='国结大户年份')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='核心客户号')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='管户部门')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Industry', verbose_name='行业门类')),
                ('type_of_3311', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.TypeOf3311', verbose_name='3311类型')),
            ],
            options={
                'verbose_name': '客户库',
                'verbose_name_plural': '客户库',
            },
        ),
        migrations.CreateModel(
            name='PretrialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=128, null=True, verbose_name='客户名称（全称）')),
                ('accept_date', models.DateField(auto_now_add=True, null=True, verbose_name='受理日期')),
                ('result', models.IntegerField(choices=[(10, '待预审'), (12, '维持原方案'), (14, '有条件通过'), (20, '通过'), (30, '续议'), (40, '否决')], default=10, verbose_name='审议结果')),
                ('reason', models.IntegerField(choices=[(0, '未知'), (1, '新增额度'), (3, '担保变更'), (4, '其他')], default=0, verbose_name='上会原因')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('order', models.IntegerField(default=0, verbose_name='上会顺位')),
                ('net_total', models.IntegerField(default=0, verbose_name='申报总敞口（万元）')),
                ('exist_net', models.IntegerField(default=0, verbose_name='已有敞口（万元）')),
                ('agree_net', models.IntegerField(default=0, verbose_name='同意敞口（万元）')),
                ('guarantee', models.TextField(blank=True, null=True, verbose_name='担保方式')),
                ('is_defuse', models.NullBooleanField(verbose_name='涉及化解')),
                ('is_green', models.NullBooleanField(verbose_name='绿色金融')),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='经营部门')),
            ],
            options={
                'verbose_name': '预审项目',
                'verbose_name_plural': '预审项目',
                'ordering': ['order', '-accept_date', 'department__display_order'],
            },
        ),
        migrations.CreateModel(
            name='PretrialMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='会议日期')),
                ('notify_date', models.DateField(blank=True, null=True, verbose_name='通报日期')),
                ('result', models.CharField(blank=True, max_length=256, null=True)),
                ('caption', models.CharField(default='待预审', max_length=32)),
            ],
            options={
                'verbose_name': '预审会',
                'verbose_name_plural': '预审会',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('status_num', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='ProjectExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_used', models.IntegerField(default=0, verbose_name='累计投放敞口')),
                ('new_net_used', models.IntegerField(default=0, verbose_name='累计投放新增敞口')),
                ('update_count', models.IntegerField(default=0, verbose_name='已更新次数')),
                ('photo_date', models.DateField(blank=True, null=True, verbose_name='快照日期')),
                ('current_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Progress', verbose_name='进度')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '项目管理',
            },
        ),
        migrations.CreateModel(
            name='ProjectRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=64, verbose_name='项目名称')),
                ('cp_con_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='授信编号')),
                ('is_green', models.BooleanField(verbose_name='绿色金融')),
                ('is_focus', models.BooleanField(default=False, verbose_name='重点项目')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('plan_pretrial_date', models.DateField(blank=True, null=True, verbose_name='计划预审')),
                ('plan_chushen', models.DateField(blank=True, null=True, verbose_name='计划初审')),
                ('plan_zhuanshen', models.DateField(blank=True, null=True, verbose_name='计划专审')),
                ('plan_xinshen', models.DateField(blank=True, null=True, verbose_name='计划信审')),
                ('plan_reply', models.DateField(blank=True, null=True, verbose_name='计划批复')),
                ('plan_luodi', models.DateField(blank=True, null=True, verbose_name='计划投放')),
                ('total_net', models.IntegerField(default=0, verbose_name='总敞口')),
                ('existing_net', models.IntegerField(default=0, verbose_name='存量敞口')),
                ('reply_content', models.TextField(blank=True, null=True, verbose_name='批复内容')),
                ('account_num', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='折算户数')),
                ('is_defuse', models.BooleanField(verbose_name='涉及化解')),
                ('is_pure_credit', models.BooleanField(verbose_name='纯信用')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='关闭日期')),
                ('tmp_close_date', models.DateField(blank=True, null=True, verbose_name='临时关闭日期')),
                ('close_reason', models.IntegerField(blank=True, choices=[(10, '预审未通过终止申报'), (20, '申报过程中终止'), (30, '分行续议后终止申报'), (35, '获批但未新增额度'), (40, '分行否决'), (50, '总行否决'), (60, '获批后不再继续'), (70, '部分落地后终止'), (80, '全部落地'), (90, '授信到期')], null=True, verbose_name='关闭理由')),
                ('whose_matter', models.IntegerField(blank=True, choices=[(0, '无责任方'), (10, '我行原因'), (20, '监管原因'), (30, '客户原因')], null=True, verbose_name='责任方')),
                ('reply_date', models.DateField(blank=True, null=True, verbose_name='批复日期')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', to='root_db.Staff', verbose_name='专审')),
            ],
            options={
                'verbose_name': '项目库',
                'verbose_name_plural': '项目库',
            },
        ),
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('display_order', models.IntegerField(default=0)),
                ('is_focus', models.BooleanField(default=False, verbose_name='是否重点产品')),
                ('acc_factor', models.FloatField(default=0, verbose_name='折算户数系数')),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Business')),
            ],
            options={
                'ordering': ('display_order',),
            },
        ),
        migrations.CreateModel(
            name='TargetTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_amount', models.FloatField(blank=True, null=True)),
                ('target_type', models.IntegerField(blank=True, choices=[(10, '计划户数'), (20, '计划金额')], null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Business')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Department')),
            ],
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.SubBusiness', verbose_name='业务品种'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.CustomerRepository', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='pre_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_approver', to='root_db.Staff', verbose_name='初审'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='pretrial_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.PretrialDocument', verbose_name='预审表'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理'),
        ),
        migrations.AddField(
            model_name='projectexecution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRepository', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='projectexecution',
            name='remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRemark', verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='progress',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Stars'),
        ),
        migrations.AddField(
            model_name='progress',
            name='suit_for_business',
            field=models.ManyToManyField(to='app_customer_repository.SubBusiness'),
        ),
        migrations.AddField(
            model_name='pretrialdocument',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.PretrialMeeting', verbose_name='预审会'),
        ),
    ]
