# Generated by Django 2.0.2 on 2018-07-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='企业名称')),
            ],
        ),
        migrations.RemoveField(
            model_name='customerstore',
            name='claimer',
        ),
        migrations.RemoveField(
            model_name='customerstore',
            name='district',
        ),
        migrations.RemoveField(
            model_name='customerstore',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='customerstore',
            name='type_of_3311',
        ),
        migrations.DeleteModel(
            name='CustomerStore',
        ),
    ]
