# Generated by Django 2.0.2 on 2018-07-09 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0023_typeof3311_remark'),
        ('app_customer_repository', '0002_auto_20180709_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrepository',
            name='claimer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.SubDepartment', verbose_name='认领'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='核心客户号'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Industry'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='inter_clearing_2017',
            field=models.IntegerField(default=0, verbose_name='2017年国际结算（万元）'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='is_strategy',
            field=models.BooleanField(default=False, verbose_name='是否战略客户'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='simple_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='stockholder',
            field=models.IntegerField(blank=True, choices=[(1, '国有'), (2, '民营'), (3, '外资')], null=True),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='taxes_2017',
            field=models.IntegerField(default=0, verbose_name='2017年纳税（万元）'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='type_of_3311',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.TypeOf3311', verbose_name='3311类型'),
        ),
    ]
