# Generated by Django 2.0.2 on 2018-07-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0002_auto_20180713_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexecution',
            name='photo_date',
            field=models.DateField(blank=True, null=True, verbose_name='快照日期'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='tmp_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='临时关闭日期'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='whose_matter',
            field=models.IntegerField(blank=True, choices=[(10, '我行原因'), (20, '监管原因'), (30, '客户原因')], null=True),
        ),
    ]
