# Generated by Django 2.0.2 on 2018-07-16 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0003_auto_20180716_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexecution',
            name='event',
            field=models.IntegerField(blank=True, choices=[(10, '预审/立项'), (20, '初审'), (30, '专审'), (40, '信审'), (50, '批复'), (60, '投放'), (70, '关闭')], null=True),
        ),
        migrations.AlterField(
            model_name='projectexecution',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
