# Generated by Django 2.0.2 on 2018-07-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0003_auto_20180709_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('status_num', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectExcution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='事件日期')),
                ('update_times', models.IntegerField(default=0, verbose_name='更新次数')),
                ('update_date', models.DateField(auto_now=True)),
                ('is_newest', models.BooleanField(default=False)),
                ('stars', models.CharField(blank=True, max_length=32, null=True, verbose_name='重点项目标识')),
                ('remark', models.CharField(blank=True, max_length=512, null=True)),
                ('progress', models.ManyToManyField(to='app_customer_repository.Progress')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='项目名称')),
                ('cp_con_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='授信编号')),
                ('is_green', models.BooleanField(default=False, verbose_name='绿色金融')),
                ('pretrial_date', models.DateField(blank=True, null=True, verbose_name='预审日期')),
                ('pretrial_file', models.CharField(blank=True, max_length=128, null=True, verbose_name='预审表')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('total_apply_net', models.IntegerField(default=0, verbose_name='申报总敞口（万元）')),
                ('account_num', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='折算户数')),
                ('newly_increase_net', models.IntegerField(default=0, verbose_name='其中存量新增敞口（万元）')),
                ('is_defuse', models.BooleanField(default=False, verbose_name='涉及化解')),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='关闭日期')),
            ],
        ),
        migrations.CreateModel(
            name='SubBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32)),
                ('superior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Business')),
            ],
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='credit_file',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='信贷文件'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.SubBusiness'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.CustomerRepository'),
        ),
        migrations.AddField(
            model_name='projectexcution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRepository'),
        ),
        migrations.AddField(
            model_name='progress',
            name='suit_for_business',
            field=models.ManyToManyField(to='app_customer_repository.SubBusiness'),
        ),
    ]
