# Generated by Django 2.0.2 on 2018-07-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0004_auto_20180710_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subbusiness',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
