# Generated by Django 2.0.2 on 2018-07-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0005_auto_20180710_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
    ]
