# Generated by Django 2.0.2 on 2018-07-11 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0006_progress_display_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PretrialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(blank=True, max_length=128, null=True, verbose_name='预审表路径')),
            ],
        ),
        migrations.CreateModel(
            name='PretrialMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(blank=True, null=True, verbose_name='会议日期')),
                ('notify_date', models.DateField(blank=True, null=True, verbose_name='通报日期')),
                ('result', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='projectexcution',
            old_name='update_times',
            new_name='update_count',
        ),
        migrations.RemoveField(
            model_name='projectexcution',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='projectexcution',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='projectrepository',
            name='pretrial_date',
        ),
        migrations.RemoveField(
            model_name='projectrepository',
            name='pretrial_file',
        ),
        migrations.AddField(
            model_name='projectexcution',
            name='current_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Progress', verbose_name='进度'),
        ),
        migrations.AddField(
            model_name='projectexcution',
            name='event',
            field=models.IntegerField(blank=True, choices=[(30, '进度变更'), (40, '流程中止'), (50, '获批'), (55, '续议'), (56, '分行否决'), (58, '总行否决'), (60, '投放'), (70, '未完终止'), (80, '完全落地')], null=True),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='is_pure_credit',
            field=models.BooleanField(default=False, verbose_name='纯信用'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='newly_increase_net',
            field=models.IntegerField(default=0, verbose_name='存量敞口（万元）'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='total_apply_net',
            field=models.IntegerField(default=0, verbose_name='申报敞口（万元）'),
        ),
        migrations.AddField(
            model_name='pretrialdocument',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.PretrialMeeting'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='pretrial_doc',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.PretrialDocument', verbose_name='预审表'),
        ),
    ]
