# Generated by Django 2.0.2 on 2018-07-18 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0023_typeof3311_remark'),
        ('app_customer_repository', '0007_remove_projectexecution_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrepository',
            name='claimer',
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='支行'),
        ),
    ]
