# Generated by Django 2.0.2 on 2018-07-11 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0023_typeof3311_remark'),
        ('app_customer_repository', '0007_auto_20180711_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.IntegerField(blank=True, choices=[(40, '流程中止'), (50, '获批'), (55, '续议'), (56, '分行否决'), (58, '总行否决'), (60, '投放'), (70, '未完终止'), (80, '完全落地')], null=True)),
                ('event_date', models.DateField(blank=True, null=True, verbose_name='事件日期')),
                ('update_count', models.IntegerField(default=0, verbose_name='更新次数')),
                ('update_date', models.DateField(auto_now=True)),
                ('is_newest', models.BooleanField(default=False)),
                ('borrow', models.IntegerField(default=0, verbose_name='本次投放（万元）')),
                ('remark', models.CharField(blank=True, max_length=512, null=True)),
                ('current_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Progress', verbose_name='进度')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectexcution',
            name='current_progress',
        ),
        migrations.RemoveField(
            model_name='projectexcution',
            name='project',
        ),
        migrations.RemoveField(
            model_name='customerrepository',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='pretrialdocument',
            name='document',
        ),
        migrations.AddField(
            model_name='pretrialdocument',
            name='accept_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pretrialdocument',
            name='document_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='already_used_new_net',
            field=models.IntegerField(default=0, verbose_name='已投新增敞口（万元）'),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff'),
        ),
        migrations.DeleteModel(
            name='ProjectExcution',
        ),
        migrations.AddField(
            model_name='projectexecution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRepository'),
        ),
    ]
