# Generated by Django 2.0.2 on 2018-07-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0008_auto_20180711_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexecution',
            options={'get_latest_by': 'update_date', 'ordering': ('-update_date',)},
        ),
        migrations.RemoveField(
            model_name='projectexecution',
            name='is_newest',
        ),
        migrations.AlterField(
            model_name='projectexecution',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
