# Generated by Django 2.0.2 on 2018-07-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0009_auto_20180712_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectexecution',
            name='is_last_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='is_focus',
            field=models.BooleanField(default=False, verbose_name='重点项目'),
        ),
        migrations.AlterField(
            model_name='projectexecution',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='progress',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Stars'),
        ),
    ]
