# Generated by Django 2.0.2 on 2018-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0011_auto_20180712_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrepository',
            name='stockholder',
            field=models.IntegerField(blank=True, choices=[(10, '国有'), (20, '民营'), (30, '外资')], null=True),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='close_reason',
            field=models.IntegerField(blank=True, choices=[(10, '')], null=True),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='whose_matter',
            field=models.IntegerField(blank=True, choices=[(10, '')], null=True),
        ),
        migrations.DeleteModel(
            name='CloseReason',
        ),
        migrations.DeleteModel(
            name='InCharge',
        ),
    ]
