# Generated by Django 2.0.4 on 2018-08-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0019_subbusiness_is_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbusiness',
            name='acc_factor',
            field=models.FloatField(default=0, verbose_name='折算户数系数'),
        ),
    ]
