# Generated by Django 2.0.4 on 2018-08-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0020_subbusiness_acc_factor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status_num',
            field=models.IntegerField(default=0),
        ),
    ]
