# Generated by Django 2.0.2 on 2018-08-31 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0025_auto_20180830_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrepository',
            name='inter_clearing_2017',
        ),
        migrations.RemoveField(
            model_name='customerrepository',
            name='taxes_2017',
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='inter_clearing_years',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='国结大户年份'),
        ),
        migrations.AddField(
            model_name='customerrepository',
            name='tax_years',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='纳税大户年份'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='close_reason',
            field=models.IntegerField(blank=True, choices=[(10, '预审未通过终止申报'), (20, '申报过程中终止'), (30, '分行续议后终止申报'), (35, '获批但未新增额度'), (40, '分行否决'), (50, '总行否决'), (60, '获批后不再继续'), (70, '部分落地后终止'), (90, '授信到期')], null=True, verbose_name='关闭理由'),
        ),
    ]
