# Generated by Django 2.1.1 on 2018-09-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0034_auto_20180920_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretrialdocument',
            name='customer_name',
            field=models.CharField(max_length=128, null=True, verbose_name='预审表'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='经营部门'),
        ),
    ]
