# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abs',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='defuse',
            name='customer',
        ),
        migrations.AddField(
            model_name='creditcustomer',
            name='ABS_expire',
            field=models.DateField(blank=True, null=True, verbose_name='ABS到期日'),
        ),
        migrations.AddField(
            model_name='creditcustomer',
            name='defuse_expire',
            field=models.DateField(blank=True, null=True, verbose_name='化解到期日'),
        ),
        migrations.DeleteModel(
            name='ABS',
        ),
        migrations.DeleteModel(
            name='Defuse',
        ),
    ]
