# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0004_contributor_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='approve_line',
            field=models.CharField(default='', max_length=8, verbose_name='审批条线'),
        ),
    ]
