# Generated by Django 2.0.4 on 2018-05-02 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0007_auto_20180502_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
    ]
