# Generated by Django 2.0.2 on 2018-05-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0008_auto_20180502_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='saving_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='储蓄余额（万元）'),
        ),
        migrations.AddField(
            model_name='contributor',
            name='saving_yd_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='储蓄日均（万元）'),
        ),
    ]
