# Generated by Django 2.0.2 on 2018-06-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0010_auto_20180619_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
