# Generated by Django 2.0.2 on 2018-06-19 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0021_auto_20180509_1424'),
        ('deposit_and_credit', '0011_contributor_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff'),
        ),
    ]
