# Generated by Django 2.0.2 on 2018-06-20 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0012_contributor_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expireprompt',
            name='explain_img',
            field=models.ImageField(blank=True, null=True, upload_to='\\deposit_and_credit\\explain'),
        ),
    ]
