# Generated by Django 2.0.2 on 2018-06-20 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0022_auto_20180620_1118'),
        ('deposit_and_credit', '0013_auto_20180620_1118'),
    ]


