# Generated by Django 2.0.2 on 2018-06-22 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0015_auto_20180621_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireprompt',
            name='punishment',
            field=models.IntegerField(default=0, verbose_name='扣罚金额'),
        ),
    ]
