# Generated by Django 2.0.2 on 2018-06-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0017_auto_20180622_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expireprompt',
            name='is_finished',
        ),
    ]
