# Generated by Django 2.0.4 on 2018-09-24 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0029_auto_20180901_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contributor',
            options={'ordering': ['-data_date', 'department__display_order', '-customer__series__gov_plat_lev'], 'verbose_name': '贡献度名单', 'verbose_name_plural': '贡献度名单'},
        ),
        migrations.AlterField(
            model_name='contributor',
            name='approve_line',
            field=models.CharField(choices=[('', '无贷'), ('地区', '地区'), ('小微', '小微')], default='', max_length=8, verbose_name='审批条线'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='业务到期'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='invest_banking',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='投行业务'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='is_green_finance',
            field=models.BooleanField(default=False, verbose_name='绿色金融'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='loan',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='贷款含ABS余额'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='loan_interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='贷款年息'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='loan_rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='加权利率'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='lr_BAB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='全额银票'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='net_BAB',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='银票净额'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='net_GL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='保函净额'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='net_TF',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='贸易融资净额'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='net_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='一般用信净额'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='saving_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='储蓄余额'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='saving_yd_avg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='储蓄日均'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理'),
        ),
    ]
