# Generated by Django 2.1.1 on 2018-09-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0030_auto_20180924_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Department', verbose_name='经营部门'),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff', verbose_name='客户经理'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xvshouxin_approver', to='root_db.Staff', verbose_name='专审'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='current_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_customer_repository.Progress', verbose_name='系统进度'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='pre_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='xvshouxin_pre_approver', to='root_db.Staff', verbose_name='初审'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff', verbose_name='客户经理'),
        ),
    ]
