# Generated by Django 2.1.1 on 2019-01-17 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0046_auto_20190117_1128'),
        ('deposit_and_credit', '0031_auto_20180928_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExpire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_amount', models.IntegerField(default=0, verbose_name='金额')),
                ('business', models.CharField(blank=True, max_length=8, null=True, verbose_name='业务种类')),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deposit_and_credit.ExpirePrompt')),
            ],
            options={
                'verbose_name': '业务到期记录',
                'verbose_name_plural': '业务到期记录',
            },
        ),
        migrations.CreateModel(
            name='LoanDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(choices=[('dld', '短期流贷'), ('zld', '中期流贷'), ('xmd', '项目贷款')], max_length=8)),
                ('now_rate', models.FloatField(default=0, verbose_name='当前利率上浮(%)')),
                ('now_deposit_avg', models.IntegerField(default=0, verbose_name='当前存款沉淀率(%)')),
                ('plan_amount', models.IntegerField(default=0, verbose_name='拟放金额')),
                ('plan_rate', models.IntegerField(default=0, verbose_name='利率拟上浮(%)')),
                ('plan_depo_ratio', models.IntegerField(default=0, verbose_name='预计存款沉淀率(%)')),
                ('plan_date', models.DateField(blank=True, null=True, verbose_name='预计投放日期')),
                ('expection', models.IntegerField(default=100, verbose_name='月底投放期望')),
                ('remark', models.CharField(blank=True, max_length=512, null=True, verbose_name='备注2')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='办结日')),
                ('existing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deposit_and_credit.BusinessExpire', verbose_name='存量规模')),
                ('new_increase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRepository', verbose_name='新增规模')),
            ],
            options={
                'verbose_name': '贷款需求',
                'verbose_name_plural': '贷款需求',
            },
        ),
    ]
