# Generated by Django 2.1.1 on 2019-01-17 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0031_auto_20190117_1334'),
        ('deposit_and_credit', '0032_businessexpire_loandemand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessexpire',
            name='prompt',
        ),
        migrations.AddField(
            model_name='loandemand',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='existing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deposit_and_credit.ExpirePrompt', verbose_name='存量规模'),
        ),
        migrations.DeleteModel(
            name='BusinessExpire',
        ),
    ]
