# Generated by Django 2.1.1 on 2019-01-17 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0034_auto_20190117_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='expect',
            field=models.IntegerField(default=100, verbose_name='把握(%)'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='now_rate',
            field=models.IntegerField(default=0, verbose_name='当前利率上浮(%)'),
        ),
    ]
