# Generated by Django 2.1.1 on 2019-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0035_auto_20190117_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandemand',
            name='customer',
        ),
        migrations.AddField(
            model_name='loandemand',
            name='add_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='添加日期'),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='already_achieved',
            field=models.IntegerField(default=0, verbose_name='已放金额'),
        ),
    ]
