# Generated by Django 2.1.1 on 2019-01-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0036_auto_20190121_1445'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandemand',
            name='existing_lu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scraper.LuLedger', verbose_name='放款台账记录'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='business',
            field=models.CharField(choices=[('dq', '短期流贷'), ('zq', '中期流贷'), ('xm', '项目贷款')], max_length=8, verbose_name='业务种类'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='now_deposit_ratio',
            field=models.IntegerField(default=0, verbose_name='当前存款金额'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='now_rate',
            field=models.FloatField(default=0, verbose_name='当前利率'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_deposit_ratio',
            field=models.IntegerField(default=0, verbose_name='预计存款金额'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_rate',
            field=models.IntegerField(default=0, verbose_name='拟放利率'),
        ),
    ]
