# Generated by Django 2.1.1 on 2019-02-01 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0031_auto_20190117_1334'),
        ('deposit_and_credit', '0038_auto_20190122_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandemand',
            name='existing',
        ),
        migrations.RemoveField(
            model_name='loandemand',
            name='existing_lu',
        ),
        migrations.RemoveField(
            model_name='loandemand',
            name='now_deposit_ratio',
        ),
        migrations.RemoveField(
            model_name='loandemand',
            name='now_rate',
        ),
        migrations.AddField(
            model_name='loandemand',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='contract',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='放款合同号'),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='expire_amount',
            field=models.IntegerField(default=0, verbose_name='存量到期金额'),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='到期日'),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='expire_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deposit_and_credit.ExpirePrompt', verbose_name='到期提示'),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='last_update',
            field=models.DateField(auto_now=True, null=True, verbose_name='最后更新'),
        ),
        migrations.AddField(
            model_name='loandemand',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scraper.DcmsBusiness', verbose_name='业务种类'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='new_increase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRepository', verbose_name='新增项目'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='拟放金额'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_deposit_ratio',
            field=models.IntegerField(blank=True, null=True, verbose_name='预计存款回报'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='拟放利率'),
        ),
    ]
