# Generated by Django 2.1.1 on 2019-02-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0039_auto_20190201_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandemand',
            name='this_month_leishou',
            field=models.IntegerField(default=0, verbose_name='当月累收'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='already_achieved',
            field=models.IntegerField(default=0, verbose_name='当月累放'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='customer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='客户'),
        ),
    ]
