# Generated by Django 2.1.1 on 2019-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0041_remove_loandemand_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='add_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间'),
        ),
    ]
