# Generated by Django 2.1.1 on 2019-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0042_auto_20190213_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注（规模相关）'),
        ),
    ]
