# Generated by Django 2.1.1 on 2019-02-27 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0043_auto_20190214_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
    ]
