# Generated by Django 2.1.1 on 2019-02-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0045_auto_20190227_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loandemand',
            options={'ordering': ('staff__sub_department__superior__display_order', '-add_time'), 'verbose_name': '贷款需求', 'verbose_name_plural': '贷款需求'},
        ),
    ]
