# Generated by Django 2.1.1 on 2019-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0046_auto_20190228_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='contract',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='放款合同号'),
        ),
    ]
