# Generated by Django 2.1.1 on 2019-03-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0047_auto_20190307_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanDemandForThisMonth',
            fields=[
            ],
            options={
                'verbose_name': '本月地区贷款规模安排',
                'verbose_name_plural': '本月地区贷款规模安排',
                'proxy': True,
                'indexes': [],
            },
            bases=('deposit_and_credit.loandemand',),
        ),
    ]
