# Generated by Django 2.1.1 on 2019-03-20 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0049_creditamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expireprompt',
            options={'verbose_name': '业务到期提示', 'verbose_name_plural': '业务到期提示'},
        ),
    ]
