# Generated by Django 2.1.1 on 2019-03-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0050_auto_20190320_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='plan_amount',
            field=models.IntegerField(default=0, verbose_name='拟放金额'),
        ),
    ]
