# Generated by Django 2.1.1 on 2019-05-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0053_auto_20190515_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loandemand',
            options={'ordering': ('-add_time', 'staff', 'staff__sub_department__superior__display_order'), 'verbose_name': '贷款需求', 'verbose_name_plural': '贷款需求'},
        ),
    ]
