# Generated by Django 2.1.1 on 2019-05-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0054_auto_20190517_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loandemand',
            options={'ordering': ('plan_date', 'staff__sub_department__superior__display_order', 'staff'), 'verbose_name': '贷款需求', 'verbose_name_plural': '贷款需求'},
        ),
    ]
