# Generated by Django 2.1.1 on 2019-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0055_auto_20190521_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='拟投/所属月份'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注*'),
        ),
    ]
