# Generated by Django 2.1.1 on 2019-05-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0056_auto_20190523_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loandemand',
            options={'ordering': ('-add_time', 'staff__sub_department__superior__display_order', 'staff'), 'verbose_name': '贷款需求', 'verbose_name_plural': '贷款需求'},
        ),
        migrations.AlterModelOptions(
            name='loandemandforthismonth',
            options={'verbose_name': '本月规模总帐', 'verbose_name_plural': '本月规模总帐'},
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
