# Generated by Django 2.1.1 on 2019-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0057_auto_20190529_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandemand',
            name='original_plan_amount',
            field=models.IntegerField(default=0, verbose_name='原拟放'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_amount',
            field=models.IntegerField(default=0, verbose_name='当前拟放'),
        ),
    ]
