# Generated by Django 2.1.1 on 2019-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0058_auto_20190605_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loandemand',
            name='original_plan_amount',
            field=models.IntegerField(default=0, verbose_name='原计划转贷'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_date',
            field=models.DateField(default='', verbose_name='拟投/所属月份'),
        ),
    ]
