# Generated by Django 2.1.1 on 2019-06-18 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0061_auto_20190605_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandemand',
            name='increase_type',
            field=models.IntegerField(choices=[(0, '-'), (10, '新增'), (15, '存量+新增'), (20, '存量收回后续贷')], default=0, verbose_name='新增类型'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='original_plan_amount',
            field=models.IntegerField(default=0, verbose_name='月初拟放'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='plan_date',
            field=models.DateField(blank=True, null=True, verbose_name='拟投/所属月份'),
        ),
    ]
