# Generated by Django 2.1.1 on 2019-06-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0062_auto_20190618_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='loandemand',
            name='is_low_risk',
            field=models.BooleanField(default=False, verbose_name='低风险'),
        ),
        migrations.AlterField(
            model_name='loandemand',
            name='increase_type',
            field=models.IntegerField(choices=[(0, '-'), (10, '新增'), (15, '存量+新增'), (20, '存量')], default=0, verbose_name='新增类型'),
        ),
    ]
