# Generated by Django 2.1.1 on 2019-07-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0063_auto_20190624_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireprompt',
            name='approve_date',
            field=models.DateField(blank=True, null=True, verbose_name='续授信批复日'),
        ),
    ]
