# Generated by Django 2.1.1 on 2018-09-20 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root_db', '0001_initial'),
        ('app_customer_repository', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionTrees',
            fields=[
                ('data_date', models.DateField(primary_key=True, serialize=False, verbose_name='数据日期')),
                ('contribution_tree', models.TextField(verbose_name='贡献度结构树')),
            ],
        ),
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve_line', models.CharField(default='', max_length=8, verbose_name='审批条线')),
                ('loan_rate', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='加权利率（%）')),
                ('loan_interest', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='贷款年息（万元）')),
                ('loan', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='贷款含ABS余额（万元）')),
                ('net_BAB', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='银票净额（万元）')),
                ('net_TF', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='贸易融资净额（万元）')),
                ('net_GL', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='保函净额（万元）')),
                ('net_total', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='一般用信净额（万元）')),
                ('lr_BAB', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='全额银票（万元）')),
                ('expire_date', models.DateField(blank=True, null=True)),
                ('invest_banking', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='投行业务（万元）')),
                ('invest_expire', models.DateField(blank=True, null=True, verbose_name='投行到期日')),
                ('ABS_expire', models.DateField(blank=True, null=True, verbose_name='ABS到期日')),
                ('defuse_expire', models.DateField(blank=True, null=True, verbose_name='化解到期日')),
                ('data_date', models.DateField(blank=True, null=True)),
                ('saving_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='储蓄余额（万元）')),
                ('saving_yd_avg', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='储蓄日均（万元）')),
                ('is_green_finance', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='经营部门')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff')),
            ],
            options={
                'verbose_name_plural': '回报客户清单',
            },
        ),
        migrations.CreateModel(
            name='ExpirePrompt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='到期日')),
                ('remark', models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='备注')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='办结日期')),
                ('punishment', models.IntegerField(default=0, verbose_name='扣罚金额')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('apply_type', models.IntegerField(choices=[(1, '如期'), (2, '暂缓'), (3, '退出')], default=1, verbose_name='续做')),
                ('chushen', models.DateField(blank=True, null=True, verbose_name='预计初审')),
                ('reply', models.DateField(blank=True, null=True, verbose_name='预计批复')),
                ('cp_num', models.CharField(blank=True, max_length=32, null=True, verbose_name='授信编号')),
                ('progress_update_date', models.DateField(blank=True, null=True)),
                ('remark_update_date', models.DateField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xvshouxin_approver', to='root_db.Staff', verbose_name='专审')),
                ('current_progress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Progress', verbose_name='系统进度')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户')),
                ('pre_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xvshouxin_pre_approver', to='root_db.Staff', verbose_name='初审')),
                ('staff_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理')),
            ],
        ),
    ]
