# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-12 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0003_auto_20180412_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='data_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
