# Generated by Django 2.0.2 on 2018-06-19 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0009_auto_20180510_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireprompt',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='explain_img',
            field=models.ImageField(blank=True, null=True, upload_to='explain'),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='remark',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany'),
        ),
    ]
