# Generated by Django 2.0.2 on 2018-06-27 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0022_auto_20180620_1118'),
        ('deposit_and_credit', '0018_remove_expireprompt_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireprompt',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff'),
        ),
    ]
