# Generated by Django 2.0.2 on 2018-07-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0022_contributor_invest_expire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departmentdeposit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='departmentdeposit',
            name='sub_department',
        ),
        migrations.AlterUniqueTogether(
            name='industrydeposit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='industrydeposit',
            name='industry',
        ),
        migrations.DeleteModel(
            name='DepartmentDeposit',
        ),
        migrations.DeleteModel(
            name='IndustryDeposit',
        ),
    ]
