# Generated by Django 2.0.4 on 2018-08-31 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0026_auto_20180831_1037'),
        ('deposit_and_credit', '0023_auto_20180724_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expireprompt',
            name='explain',
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='apply_type',
            field=models.IntegerField(choices=[(1, '如期'), (2, '暂缓'), (3, '退出')], default=1, verbose_name='续做计划'),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='chushen',
            field=models.DateField(blank=True, null=True, verbose_name='预计初审'),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='current_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Progress', verbose_name='当前进度'),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='reply',
            field=models.DateField(blank=True, null=True, verbose_name='预计批复'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='到期日'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='remark',
            field=models.CharField(default='', max_length=512, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='staff_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理'),
        ),
    ]
