# Generated by Django 2.0.4 on 2018-09-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0024_auto_20180831_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireprompt',
            name='cp_num',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='授信编号'),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='progress_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='current_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.Progress', verbose_name='系统进度'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
    ]
