# Generated by Django 2.0.4 on 2018-09-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0025_auto_20180901_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireprompt',
            name='remark_update_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='apply_type',
            field=models.IntegerField(choices=[(1, '如期'), (2, '暂缓'), (3, '退出')], default=1, verbose_name='续做'),
        ),
    ]
