# Generated by Django 2.0.4 on 2018-09-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0027_auto_20180820_1318'),
        ('deposit_and_credit', '0026_auto_20180901_0531'),
    ]

    operations = [
        migrations.AddField(
            model_name='expireprompt',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xvshouxin_approver', to='root_db.Staff', verbose_name='专审'),
        ),
        migrations.AddField(
            model_name='expireprompt',
            name='pre_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xvshouxin_pre_approver', to='root_db.Staff', verbose_name='初审'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='remark',
            field=models.CharField(blank=True, default='', max_length=512, null=True, verbose_name='备注'),
        ),
    ]
