# Generated by Django 2.0.4 on 2018-09-01 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0028_auto_20180901_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expireprompt',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xvshouxin_approver', to='root_db.Staff', verbose_name='专审'),
        ),
        migrations.AlterField(
            model_name='expireprompt',
            name='pre_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xvshouxin_pre_approver', to='root_db.Staff', verbose_name='初审'),
        ),
    ]
