# Generated by Django 2.0.2 on 2018-07-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0009_auto_20180718_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='replay_date',
            field=models.DateField(blank=True, null=True, verbose_name='批复日期'),
        ),
    ]
