# Generated by Django 2.0.2 on 2018-07-18 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0010_projectrepository_replay_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrepository',
            old_name='replay_date',
            new_name='reply_date',
        ),
    ]
