# Generated by Django 2.0.2 on 2018-07-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0011_auto_20180718_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexecution',
            name='this_time_used',
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='close_reason',
            field=models.IntegerField(blank=True, choices=[(10, '预审未通过终止申报'), (20, '申报过程中终止'), (30, '分行续议后终止申报'), (40, '分行否决'), (50, '总行否决'), (60, '获批后不再继续'), (70, '部分落地后终止'), (80, '全部落地'), (90, '授信到期')], null=True),
        ),
    ]
