# Generated by Django 2.0.2 on 2018-07-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0013_projectrepository_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrepository',
            name='customer',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='核心客户号'),
        ),
    ]
