# Generated by Django 2.0.2 on 2018-07-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0014_auto_20180720_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrepository',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='核心客户号'),
        ),
    ]
