# Generated by Django 2.0.2 on 2018-07-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0015_auto_20180720_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexecution',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectexecution',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='projectexecution',
            name='update_date',
        ),
    ]
