# Generated by Django 2.0.2 on 2018-07-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0026_auto_20180725_0829'),
        ('app_customer_repository', '0016_auto_20180720_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='pre_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pre_approver', to='root_db.Staff', verbose_name='初审'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approver', to='root_db.Staff', verbose_name='专审'),
        ),
    ]
