# Generated by Django 2.0.2 on 2018-07-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0017_auto_20180726_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targettask',
            name='target_type',
            field=models.IntegerField(blank=True, choices=[(10, '计划户数'), (20, '计划金额')], null=True),
        ),
    ]
