# Generated by Django 2.0.4 on 2018-08-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0021_auto_20180805_0855'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ('display_order',)},
        ),
        migrations.AlterModelOptions(
            name='subbusiness',
            options={'ordering': ('display_order',)},
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='管户部门'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Industry', verbose_name='行业门类'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='simple_name',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='企业简称'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='stockholder',
            field=models.IntegerField(blank=True, choices=[(10, '国有'), (20, '民营'), (30, '外资')], null=True, verbose_name='控股方式'),
        ),
        migrations.AlterField(
            model_name='projectexecution',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRepository', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='projectexecution',
            name='remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRemark', verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.SubBusiness', verbose_name='业务品种'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='close_reason',
            field=models.IntegerField(blank=True, choices=[(10, '预审未通过终止申报'), (20, '申报过程中终止'), (30, '分行续议后终止申报'), (35, '获批但未新增额度'), (40, '分行否决'), (50, '总行否决'), (60, '获批后不再继续'), (70, '部分落地后终止'), (80, '全部落地'), (90, '授信到期')], null=True, verbose_name='关闭理由'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.CustomerRepository', verbose_name='客户'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='whose_matter',
            field=models.IntegerField(blank=True, choices=[(10, '我行原因'), (20, '监管原因'), (30, '客户原因')], null=True, verbose_name='责任方'),
        ),
    ]
