# Generated by Django 2.0.2 on 2018-08-30 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0022_auto_20180820_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrepository',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Department', verbose_name='管户部门'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Industry', verbose_name='行业门类'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='is_strategy',
            field=models.BooleanField(verbose_name='是否战略客户'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='simple_name',
            field=models.CharField(max_length=32, unique=True, verbose_name='企业简称'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='stockholder',
            field=models.IntegerField(choices=[(10, '国有'), (20, '民营'), (30, '外资')], verbose_name='控股方式'),
        ),
        migrations.AlterField(
            model_name='customerrepository',
            name='type_of_3311',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.TypeOf3311', verbose_name='3311类型'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='whose_matter',
            field=models.IntegerField(blank=True, choices=[(0, '无责任方'), (10, '我行原因'), (20, '监管原因'), (30, '客户原因')], null=True, verbose_name='责任方'),
        ),
    ]
