# Generated by Django 2.0.2 on 2018-08-30 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0023_auto_20180830_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrepository',
            name='is_defuse',
            field=models.BooleanField(verbose_name='涉及化解'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='is_green',
            field=models.BooleanField(verbose_name='绿色金融'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='is_pure_credit',
            field=models.BooleanField(verbose_name='纯信用'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='project_name',
            field=models.CharField(max_length=64, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理'),
        ),
    ]
