# Generated by Django 2.0.2 on 2018-08-30 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0024_auto_20180830_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexecution',
            name='remark',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='app_customer_repository.ProjectRemark', verbose_name='备注'),
        ),
    ]
