# Generated by Django 2.0.2 on 2018-09-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0026_auto_20180831_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretrialdocument',
            name='result',
            field=models.IntegerField(choices=[(10, '待预审'), (12, '维持原方案'), (14, '有条件通过'), (20, '通过'), (30, '续议'), (40, '否决')], default=10),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='close_reason',
            field=models.IntegerField(blank=True, choices=[(10, '预审未通过终止申报'), (20, '申报过程中终止'), (30, '分行续议后终止申报'), (35, '获批但未新增额度'), (40, '分行否决'), (50, '总行否决'), (60, '获批后不再继续'), (70, '部分落地后终止'), (80, '全部落地'), (90, '授信到期')], null=True, verbose_name='关闭理由'),
        ),
    ]
