# Generated by Django 2.0.2 on 2018-09-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0027_auto_20180911_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretrialmeeting',
            name='caption',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
