# Generated by Django 2.1.1 on 2018-09-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0031_auto_20180919_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerrepository',
            options={'verbose_name': '客户库', 'verbose_name_plural': '客户库'},
        ),
        migrations.AlterModelOptions(
            name='pretrialdocument',
            options={'verbose_name': '预审项目', 'verbose_name_plural': '预审项目'},
        ),
        migrations.AlterModelOptions(
            name='pretrialmeeting',
            options={'verbose_name': '预审会', 'verbose_name_plural': '预审会'},
        ),
        migrations.AlterModelOptions(
            name='projectexecution',
            options={'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AlterModelOptions(
            name='projectrepository',
            options={'verbose_name': '项目库', 'verbose_name_plural': '项目库'},
        ),
        migrations.RenameField(
            model_name='pretrialdocument',
            old_name='document_name',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='pretrialmeeting',
            name='folder',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='预审表路径'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='reason',
            field=models.IntegerField(choices=[(0, '未知'), (1, '新增额度'), (3, '担保变更'), (4, '其他')], default=0, verbose_name='预审原因'),
        ),
    ]
