# Generated by Django 2.1.1 on 2018-09-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0033_remove_pretrialmeeting_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pretrialmeeting',
            options={'ordering': ('-id',), 'verbose_name': '预审会', 'verbose_name_plural': '预审会'},
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='is_defuse',
            field=models.NullBooleanField(verbose_name='涉及化解'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='is_green',
            field=models.NullBooleanField(verbose_name='绿色金融'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='order',
            field=models.IntegerField(default=0, verbose_name='上会顺位'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='reason',
            field=models.IntegerField(choices=[(0, '未知'), (1, '新增额度'), (3, '担保变更'), (4, '其他')], default=0, verbose_name='上会原因'),
        ),
    ]
