# Generated by Django 2.0.4 on 2018-09-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0035_auto_20180920_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pretrialdocument',
            options={'ordering': ['order', '-accept_date', 'department__display_order'], 'verbose_name': '预审项目', 'verbose_name_plural': '预审项目'},
        ),
        migrations.AddField(
            model_name='pretrialdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='预审表'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='customer_name',
            field=models.CharField(max_length=128, null=True, verbose_name='客户名称'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='reason',
            field=models.IntegerField(choices=[(0, 'unknown'), (1, '新增额度'), (2, '平移'), (3, '担保变更'), (4, '其他')], default=0, verbose_name='上会原因'),
        ),
        migrations.AlterField(
            model_name='pretrialmeeting',
            name='caption',
            field=models.CharField(default='待预审', max_length=32),
        ),
    ]
