# Generated by Django 2.0.2 on 2018-10-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0039_auto_20181029_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretrialdocument',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Industry', verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='stockholder',
            field=models.IntegerField(choices=[(0, 'unknown'), (10, '国有'), (20, '民营'), (30, '外资')], verbose_name='控股方'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='type_of_3311',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.TypeOf3311', verbose_name='3311类型'),
        ),
    ]
