# Generated by Django 2.1.1 on 2018-10-30 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0029_auto_20180928_1031'),
        ('app_customer_repository', '0040_auto_20181030_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectrepository',
            name='is_pure_credit',
        ),
        migrations.AddField(
            model_name='pretrialdocument',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff', verbose_name='客户经理'),
        ),
    ]
