# Generated by Django 2.1.1 on 2018-10-30 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0041_auto_20181030_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretrialdocument',
            name='business',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='app_customer_repository.SubBusiness', verbose_name='业务品种'),
        ),
    ]
