# Generated by Django 2.1.1 on 2018-10-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0042_pretrialdocument_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='is_specially_focus',
            field=models.BooleanField(default=False, verbose_name='是否重点跟进项目'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_customer_repository.SubBusiness', verbose_name='业务品种'),
        ),
    ]
