# Generated by Django 2.1.1 on 2018-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0043_auto_20181030_1708'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectrepository',
            options={'ordering': ['customer__department__display_order', 'customer', 'staff'], 'verbose_name': '项目库', 'verbose_name_plural': '项目库'},
        ),
        migrations.AddField(
            model_name='pretrialdocument',
            name='gov_debt_type',
            field=models.IntegerField(choices=[(0, '非政府债务'), (1, '未申报'), (2, '政府一般债务'), (3, '政府隐性债务'), (4, '自身经营债务')], default=0, verbose_name='政府债务申报类型'),
        ),
    ]
