# Generated by Django 2.1.1 on 2018-11-30 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0044_auto_20181112_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='current_progress',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_customer_repository.Progress', verbose_name='当前进度'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='gov_debt_type',
            field=models.IntegerField(choices=[(0, '未知'), (-1, '非政府债务'), (1, '未申报'), (2, '政府一般债务'), (3, '政府隐性债务'), (4, '自身经营债务')], default=0, verbose_name='政府债务申报类型'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='result',
            field=models.IntegerField(choices=[(10, '待预审'), (12, '维持原额度'), (14, '有条件通过'), (20, '通过'), (30, '续议'), (40, '否决')], default=10, verbose_name='审议结果'),
        ),
        migrations.AlterField(
            model_name='projectrepository',
            name='close_reason',
            field=models.IntegerField(blank=True, choices=[(10, '预审未通过终止申报'), (20, '申报过程中终止'), (30, '分行续议后终止申报'), (35, '获批但未新增额度'), (40, '分行否决'), (50, '总行否决'), (60, '获批后不再继续'), (70, '部分落地后终止'), (80, '全部落地'), (90, '授信到期'), (100, '其他')], null=True, verbose_name='关闭理由'),
        ),
    ]
