# Generated by Django 2.1.1 on 2019-01-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0045_auto_20181130_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ('display_order',), 'verbose_name': '进度', 'verbose_name_plural': '进度'},
        ),
        migrations.AlterField(
            model_name='business',
            name='caption',
            field=models.CharField(max_length=32, verbose_name='业务名称'),
        ),
        migrations.AlterField(
            model_name='pretrialmeeting',
            name='caption',
            field=models.CharField(default='待预审', max_length=32, verbose_name='预审会编号'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status_num',
            field=models.IntegerField(default=0, verbose_name='状态码'),
        ),
    ]
