# Generated by Django 2.1.1 on 2019-03-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0046_auto_20190117_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretrialdocument',
            name='result',
            field=models.IntegerField(choices=[(10, '待预审'), (12, '维持原额度或压缩'), (14, '有条件通过'), (20, '通过'), (30, '续议'), (40, '否决')], default=10, verbose_name='审议结果'),
        ),
    ]
