# Generated by Django 2.1.1 on 2019-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0047_auto_20190320_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='add_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
