# Generated by Django 2.1.1 on 2019-03-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0048_projectrepository_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretrialdocument',
            name='is_defuse',
            field=models.BooleanField(default=False, verbose_name='涉及化解'),
        ),
        migrations.AlterField(
            model_name='pretrialdocument',
            name='is_green',
            field=models.BooleanField(default=False, verbose_name='绿色金融'),
        ),
    ]
