# Generated by Django 2.1.1 on 2019-05-15 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0049_auto_20190325_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoringProjectForExport',
            fields=[
            ],
            options={
                'verbose_name': '储备项目下载',
                'verbose_name_plural': '储备项目下载',
                'proxy': True,
                'indexes': [],
            },
            bases=('app_customer_repository.projectrepository',),
        ),
        migrations.AlterModelOptions(
            name='projectexecution',
            options={'ordering': ('-photo_date',), 'verbose_name': '项目管理', 'verbose_name_plural': '项目管理'},
        ),
        migrations.AlterField(
            model_name='targettask',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_customer_repository.Business', verbose_name='业务种类'),
        ),
        migrations.AlterField(
            model_name='targettask',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Department', verbose_name='经营部门'),
        ),
        migrations.AlterField(
            model_name='targettask',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='时间区间——结束'),
        ),
        migrations.AlterField(
            model_name='targettask',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='时间区间——开始'),
        ),
        migrations.AlterField(
            model_name='targettask',
            name='target_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='目标数'),
        ),
        migrations.AlterField(
            model_name='targettask',
            name='target_type',
            field=models.IntegerField(blank=True, choices=[(10, '计划户数'), (20, '计划金额')], null=True, verbose_name='目标类型'),
        ),
    ]
