# Generated by Django 2.1.1 on 2019-05-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0050_auto_20190515_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='need_ignore',
            field=models.BooleanField(default=False, verbose_name='是否忽略'),
        ),
    ]
