# Generated by Django 2.1.1 on 2019-07-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0051_projectrepository_need_ignore'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrepository',
            name='luodi',
            field=models.IntegerField(default=0, verbose_name='落地金额或比例'),
        ),
    ]
