# Generated by Django 2.1.1 on 2019-08-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer_repository', '0054_auto_20190730_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectexecution',
            options={'ordering': ('-photo_date',), 'verbose_name': '项目日志', 'verbose_name_plural': '项目日志'},
        ),
        migrations.AlterModelOptions(
            name='projectrepository',
            options={'ordering': ['customer__department__display_order', 'staff__name', 'customer'], 'verbose_name': '项目库', 'verbose_name_plural': '项目库'},
        ),
        migrations.AlterModelOptions(
            name='storingprojectforexport',
            options={'verbose_name': '进行中项目', 'verbose_name_plural': '进行中项目'},
        ),
        migrations.AddField(
            model_name='projectrepository',
            name='need_hq',
            field=models.BooleanField(default=False, verbose_name='是否须报总行'),
        ),
    ]
