# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root_db', '0007_auto_20180323_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, unique=True, verbose_name='描述')),
                ('url', models.CharField(max_length=64, unique=True, verbose_name='可用url')),
                ('url_name', models.CharField(max_length=64, unique=True, verbose_name='url别名')),
                ('url_display_name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '权限信息',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'verbose_name_plural': '用户角色',
            },
        ),
        migrations.CreateModel(
            name='Role_Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_permission.Permission')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_permission.Role')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=16, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_permission.Role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='perm',
            field=models.ManyToManyField(through='app_permission.Role_Perm', to='app_permission.Permission'),
        ),
    ]
