# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root_db', '0007_auto_20180323_1550'),
        ('app_permission', '0003_auto_20180404_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, unique=True)),
                ('url_name', models.CharField(max_length=64, unique=True)),
                ('widget_type', models.SmallIntegerField(choices=[(0, None)], default=0)),
                ('display_caption', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role_Perm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_permission.Permission')),
                ('role_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_permission.Role')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=16)),
                ('roles', models.ManyToManyField(to='app_permission.Role')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(through='app_permission.Role_Perm', to='app_permission.Permission'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app_permission.Permission'),
        ),
        migrations.AddField(
            model_name='mainmenu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_permission.MainMenu'),
        ),
    ]
