# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 08:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0012_auto_20180410_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmenuitem',
            old_name='order',
            new_name='root_item_order',
        ),
    ]
