# Generated by Django 2.1.1 on 2018-09-28 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0015_auto_20180920_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenuitem',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_permission.Permission'),
        ),
        migrations.AlterField(
            model_name='mainmenuitem',
            name='parent_perm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_item', to='app_permission.Permission'),
        ),
        migrations.AlterField(
            model_name='role_perm',
            name='permission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_permission.Permission'),
        ),
        migrations.AlterField(
            model_name='role_perm',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_permission.Role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.Staff'),
        ),
    ]
