# Generated by Django 2.1.1 on 2018-10-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_permission', '0017_auto_20181001_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenuitem',
            options={'verbose_name': '菜单及功能', 'verbose_name_plural': '菜单及功能'},
        ),
    ]
