# Generated by Django 2.1.1 on 2019-01-21 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposit_and_credit', '0036_auto_20190121_1445'),
        ('root_db', '0031_auto_20190117_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpLedger',
            fields=[
                ('add_date', models.DateField(auto_now_add=True)),
                ('cp_num', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='参考编号')),
                ('is_auto_added', models.BooleanField(default=False, verbose_name='是否自动生成')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root_db.Customer', verbose_name='客户')),
            ],
        ),
        migrations.CreateModel(
            name='LuLedger',
            fields=[
                ('add_date', models.DateField(auto_now_add=True)),
                ('current_amount', models.FloatField(default=0, verbose_name='当前余额')),
                ('update_date', models.DateField(auto_now=True, verbose_name='更新日')),
                ('lu_num', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='参考编号')),
                ('cp', models.ForeignKey(blank=True, db_column='cp_num', null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.CpLedger', verbose_name='授信')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='单位名称')),
                ('loan_demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='deposit_and_credit.LoanDemand', verbose_name='规模安排')),
            ],
            options={
                'verbose_name': '放款台账',
                'verbose_name_plural': '放款台账',
            },
        ),
    ]
