# Generated by Django 2.1.1 on 2019-02-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20190201_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luledger',
            name='contract_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='信贷合同编号'),
        ),
    ]
