# Generated by Django 2.1.1 on 2019-02-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20190212_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='luledger',
            name='is_green',
            field=models.BooleanField(default=False, verbose_name='绿色金融'),
        ),
    ]
