# Generated by Django 2.1.1 on 2019-02-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_luledger_is_green'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpledger',
            options={'verbose_name': '授信台账', 'verbose_name_plural': '授信台账'},
        ),
        migrations.AlterModelOptions(
            name='luledger',
            options={'ordering': ('-add_date',), 'verbose_name': '放款台账', 'verbose_name_plural': '放款台账'},
        ),
        migrations.AlterField(
            model_name='luledger',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='currency_type',
            field=models.CharField(default='CNY', max_length=8, verbose_name='业务币种'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='pay_method',
            field=models.IntegerField(choices=[(1, '受托'), (2, '自主')], default=1, verbose_name='支付方式'),
        ),
    ]
