# Generated by Django 2.1.1 on 2019-02-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_auto_20190214_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='apply_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='申报金额'),
        ),
        migrations.AddField(
            model_name='cpledger',
            name='reply_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='批复金额'),
        ),
    ]
