# Generated by Django 2.1.1 on 2019-02-15 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0034_auto_20190214_1603'),
        ('scraper', '0008_auto_20190215_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='baozheng',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='保证担保'),
        ),
        migrations.AddField(
            model_name='cpledger',
            name='diya',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='抵押担保'),
        ),
        migrations.AddField(
            model_name='cpledger',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.Staff', verbose_name='客户经理'),
        ),
        migrations.AddField(
            model_name='cpledger',
            name='zhiya',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='质押担保'),
        ),
    ]
