# Generated by Django 2.1.1 on 2019-02-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20190215_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLeiShou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_date', models.DateField(auto_now_add=True)),
                ('contract_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='信贷合同编号')),
                ('retract_amount', models.FloatField(default=0, verbose_name='收回金额（元）')),
                ('retract_date', models.FloatField(blank=True, null=True, verbose_name='收回日期')),
            ],
            options={
                'verbose_name': '累收',
                'verbose_name_plural': '累收',
            },
        ),
    ]
