# Generated by Django 2.1.1 on 2019-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_dailyleishou'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='cp_rlk',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
