# Generated by Django 2.1.1 on 2019-02-28 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0035_accountedcompany_add_date'),
        ('scraper', '0012_auto_20190228_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpledger',
            name='customer_name',
        ),
        migrations.AddField(
            model_name='cpledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
    ]
