# Generated by Django 2.1.1 on 2019-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_auto_20190228_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='授信到期日'),
        ),
    ]
