# Generated by Django 2.1.1 on 2019-03-06 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0016_auto_20190306_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyleishou',
            name='retract_date',
            field=models.DateField(blank=True, null=True, verbose_name='收回日期'),
        ),
    ]
