# Generated by Django 2.1.1 on 2019-03-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0017_auto_20190306_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luledger',
            name='customer_code',
        ),
    ]
