# Generated by Django 2.1.1 on 2019-03-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0018_remove_luledger_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luledger',
            name='loan_demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='deposit_and_credit.LoanDemand', verbose_name='规模安排'),
        ),
    ]
