# Generated by Django 2.1.1 on 2019-03-06 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root_db', '0038_auto_20190306_1057'),
        ('scraper', '0021_auto_20190306_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyleishou',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户'),
        ),
    ]
