# Generated by Django 2.1.1 on 2019-03-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0022_dailyleishou_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='已批准'),
        ),
    ]
