# Generated by Django 2.1.1 on 2019-03-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0024_auto_20190308_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luledger',
            name='guarantee',
        ),
        migrations.AddField(
            model_name='luledger',
            name='has_baozheng',
            field=models.BooleanField(default=False, verbose_name='保证'),
        ),
        migrations.AddField(
            model_name='luledger',
            name='has_diya',
            field=models.BooleanField(default=False, verbose_name='抵押'),
        ),
        migrations.AddField(
            model_name='luledger',
            name='has_zhiya',
            field=models.BooleanField(default=False, verbose_name='质押'),
        ),
    ]
