# Generated by Django 2.1.1 on 2019-03-11 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0025_auto_20190308_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cpledger',
            name='dcms_customer_code',
        ),
        migrations.AddField(
            model_name='cpledger',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cpledger',
            name='cp_num',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='参考编号'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='cp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.CpLedger', verbose_name='授信'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='float_ratio',
            field=models.FloatField(blank=True, null=True, verbose_name='浮动比例%'),
        ),
    ]
