# Generated by Django 2.1.1 on 2019-03-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0049_creditamount'),
        ('scraper', '0026_auto_20190311_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='luledger',
            name='loan_demand',
            field=models.ManyToManyField(blank=True, null=True, to='deposit_and_credit.LoanDemand', verbose_name='贷款需求'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='currency_type',
            field=models.CharField(choices=[('CNY', '人民币'), ('USD', '美元'), ('OTHER', '其他')], default='CNY', max_length=8, verbose_name='业务币种'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='root_db.AccountedCompany', verbose_name='客户名称'),
        ),
    ]
