# Generated by Django 2.1.1 on 2019-03-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0029_luledger_rlk'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='is_virtual',
            field=models.BooleanField(default=False, verbose_name='虚拟'),
        ),
        migrations.AddField(
            model_name='cpledger',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
