# Generated by Django 2.1.1 on 2019-03-15 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0030_auto_20190313_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='cp_type',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='类型'),
        ),
    ]
