# Generated by Django 2.1.1 on 2019-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0031_cpledger_cp_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpledger',
            name='cp_type',
            field=models.CharField(blank=True, choices=[('CP', '地区'), ('SME', '小微'), ('CS', '个人')], max_length=8, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='loan_demand',
            field=models.ManyToManyField(blank=True, null=True, to='deposit_and_credit.LoanDemand', verbose_name='贷款需求'),
        ),
    ]
