# Generated by Django 2.1.1 on 2019-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0032_auto_20190318_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luledger',
            name='loan_demand',
            field=models.ManyToManyField(blank=True, to='deposit_and_credit.LoanDemand', verbose_name='贷款需求'),
        ),
    ]
