# Generated by Django 2.1.1 on 2019-03-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0034_auto_20190321_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luledger',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建于'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='lend_date',
            field=models.DateField(blank=True, null=True, verbose_name='发放日期'),
        ),
    ]
