# Generated by Django 2.1.1 on 2019-03-28 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0036_auto_20190328_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpledger',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scraper.CpLedger', verbose_name='前授信'),
        ),
        migrations.AddField(
            model_name='dailyleishou',
            name='cp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scraper.CpLedger', verbose_name='授信'),
        ),
        migrations.AddField(
            model_name='dailyleishou',
            name='lu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scraper.LuLedger', verbose_name='放款'),
        ),
        migrations.AlterField(
            model_name='luledger',
            name='lend_amount',
            field=models.FloatField(default=0, verbose_name='发放金额（元）'),
        ),
    ]
