# Generated by Django 2.1.1 on 2019-05-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0037_auto_20190328_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='LuLedgerForExport',
            fields=[
            ],
            options={
                'verbose_name': '放款台账导出',
                'verbose_name_plural': '放款台账导出',
                'proxy': True,
                'indexes': [],
            },
            bases=('scraper.luledger',),
        ),
        migrations.AlterModelOptions(
            name='dailyleishou',
            options={'ordering': ('-retract_date',), 'verbose_name': '回收', 'verbose_name_plural': '回收'},
        ),
        migrations.AlterField(
            model_name='dailyleishou',
            name='retract_amount',
            field=models.FloatField(default=0, verbose_name='收回金额（人民币，万元）'),
        ),
    ]
