# Generated by Django 2.1.1 on 2019-05-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0038_auto_20190515_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='luledger',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='luledger',
            name='lu_num',
            field=models.CharField(max_length=32, unique=True, verbose_name='放款参考编号'),
        ),
    ]
