# Generated by Django 2.1.1 on 2019-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit_and_credit', '0055_auto_20190521_0909'),
        ('scraper', '0041_remove_luledger_loan_demand'),
    ]

    operations = [
        migrations.AddField(
            model_name='luledger',
            name='loan_demand',
            field=models.ManyToManyField(blank=True, to='deposit_and_credit.LoanDemand', verbose_name='贷款需求'),
        ),
    ]
