# Generated by Django 2.1.1 on 2019-05-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0042_luledger_loan_demand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luledger',
            name='loan_demand',
        ),
    ]
