# Generated by Django 2.1.1 on 2019-07-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0044_datastorage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastorage',
            options={'ordering': ('label', 'statistic_caliber', 'data_date'), 'verbose_name': '数据记录', 'verbose_name_plural': '数据记录'},
        ),
        migrations.AlterUniqueTogether(
            name='datastorage',
            unique_together={('data_date', 'label', 'statistic_caliber')},
        ),
    ]
