# Generated by Django 2.1.1 on 2019-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0045_auto_20190715_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorage',
            name='label',
            field=models.CharField(choices=[('qkjdk', '全口径贷款余额'), ('zzydk', '制造业贷款余额'), ('mydk', '民营企业贷款余额'), ('xwdk', '小微企业贷款余额'), ('lsxdzb', '绿色信贷占比'), ('gsdk', '公司类贷款余额'), ('gsdk_no_fft', '公司类贷款去掉同业福费廷'), ('dkhs', '贷款户数')], max_length=16, null=True, verbose_name='标签'),
        ),
    ]
